- .travis.yml
- apps/volontulo/package.json
- docker-compose.yml
__Story / Bug id:__ https://github.com/stxnext-csr/volontulo/issues/503
After successfull build in master branch Travis is pushing Docker image to Dockerhub
* N/A
* N/A
After successfull build in master branch Travis is pushing Docker image to Dockerhub. It would allow to build environment from image downloaded from Dockerhub instead of building it from scratch locally.
> Travis is pushing Docker image to Dockerhub

- Dockerfile
- apps/volontulo/package.json
__Story / Bug id:__ N/A
Upgrade of NodeJS to most current version + update of all npm packages used.
* nodejs 4.2.0 -> 7.4.0
* gulp 3.6.0 -> 3.9.1
* gulp-util 3.0.6 -> 3.0.8
* gulp-sass 2.0.4 -> 3.0.0
* gulp-iconify 0.4.0 -> 0.6.0
* N/A
Build new docker image using local `Dockerfile` and check if frontent assets have been generated properly
> Update of nodejs and nodejs's packages

- .travis.yml
- fabfile.py
__Story / Bug id:__ N/A
Update testing environment after every merge to master
* fabric on after_success hook
* N/A
Check if fresh version is available on test environment
> Update testing environment after every merge to master

- .travis.yml
__Story / Bug id:__ N/A
In deployment code in Travis were missing semicolons.
* N/A
* N/A
In deployment code in Travis were missing semicolons.
> missing semicolons

- .travis.yml
__Story / Bug id:__ N/A
Provide password-aware fabric script responsible for deploing newest version from Travis.
* N/A
* N/A
N/A
> Fabric with password

- apps/volontulo/templates/common/footer.html
__Story / Bug id:__ https://github.com/CodeForPoznan/volontulo/issues/459
__Reference person:__ @mlipa
Add links in organization's section in the footer.
> [459] Refactor organization's section in the footer

- apps/volontulo/templates/common/sub-footer.html
__Reference person:__ @Bosmanfrx
Removed 2 logos from footer. Repositioned them a little.
Take a peek at footer
> Reworked footer logos a bit

- apps/volontulo/views/organizations.py
__Story / Bug id:__ https://github.com/CodeForPoznan/volontulo/issues/442
Mail sent after contact with organisation form should end up in organisation's contacts inbox
Sent message using contact organization form
> Fix receiver of contact to organisation form (fixes 442)

- backend/apps/volontulo/models.py
- backend/apps/volontulo/templates/users/user_profile.html
- backend/apps/volontulo/tests/models/test_userprofile.py
__Story / Bug id:__ https://github.com/CodeForPoznan/volontulo/issues/537
__Reference person:__ @yourgithubname
Other view of section "Działania w instytucji czy organizacji" when user is in organization.
* `apps/volontulo/tests/models/test_usersprofile.py`
> 537 feature: other section in user panel if user not in organization

- backend/apps/volontulo/authentication.py
- backend/apps/volontulo/serializers.py
- backend/apps/volontulo/urls.py
- backend/apps/volontulo/views/api.py
__Story / Bug id:__ https://github.com/CodeForPoznan/volontulo/issues/573
__Reference person:__ @magul 
Description of your changes.
API View to login
* `package`
TODO: 
Import refactor
Unit tests
IF's refactor
Logout
> [WIP] 573 Login API test view

- fabfile.py
- frontend/src/app/user.service.ts
__Story / Bug id:__ https://github.com/CodeForPoznan/volontulo/issues/577
__Reference person:__ @magul 
WIP service just for @magul
> [WIP] #577 [Angular]: user service

- frontend/src/app/organization/organization.d.ts
- frontend/src/app/organization/organization.service.spec.ts
- frontend/src/app/organization/organization.service.ts
Added service that fethces organization list / object
* `/frontend/src/app/organization/organization.service.spec.ts`
ng test
> Organization service, interface and tests

- frontend/src/app/footer/footer.component.html
> fix regulation link in footer (fixes #681)

- frontend/src/app/footer/footer.component.html
- frontend/src/app/header/header.component.html
Changed "../../assets/" to "assets/"
> fix linking to angular-based assets

- backend/apps/volontulo/views/offers.py
added: ` from django.utils.safestring import mark_safe `
and: `mark_safe`
solve the issue
Description of your changes.
* `package`
* `apps/volontulo/tests/views/test_auth.py`
> issue #714

- backend/apps/volontulo/templates/auth/login.html
- backend/apps/volontulo/templates/common/header.html
- backend/apps/volontulo/tests/views/test_auth.py
- frontend/src/app/app.component.spec.ts
- frontend/src/app/app.module.ts
- frontend/src/app/auth.models.ts
- frontend/src/app/auth.service.ts
- frontend/src/app/header/header.component.html
- frontend/src/app/header/header.component.spec.ts
- frontend/src/app/header/header.component.ts
- frontend/src/app/login/login.component.html
- frontend/src/app/login/login.component.spec.ts
- frontend/src/app/login/login.component.ts
#689
* `package`
* `apps/volontulo/tests/views/test_auth.py`
> Login moved from Django to Angular

- frontend/src/app/offers/offers.component.html
- frontend/src/app/offers/offers.component.ts
- frontend/src/app/offers/offers.model.ts
- frontend/src/app/offers/offers.service.ts
In offer component I've added for loop to add corect url to every offer as a viewUrl property (which is added to offer.model). In template offer.url was changed to offer.viewUrl.
import environment.ts in offer.component
* `package`
* `apps/volontulo/tests/views/test_auth.py`
> offer view url (#702)

- frontend/src/app/auth.service.ts
- frontend/src/app/login/login.component.html
- frontend/src/app/login/login.component.spec.ts
- frontend/src/app/login/login.component.ts
Added alert to login view, when invalid login data were provided in form.
> Login error alert

- backend/apps/volontulo/templates/common/footer.html
- frontend/src/app/footer/footer.component.html
Przyjdź na dyżur link added to strefa wolontariusza in Angular view (like it is in Django view).
> Przyjdź na dyżur link added to strefa wolontariusza

- fabfile.py
issue #784 
import secrets was moved into fab install
> import secrets was moved into fab install #784

- frontend/src/app/homepage-offer/offers.service.ts
- frontend/src/app/offers/offer-detail/offer-detail.component.html
- frontend/src/app/offers/offer-detail/offer-detail.component.ts
Changed getOfferViewUrl to navigate to Angular when clicking an offer in homepage view and added getJoinViewUrl because for now it stays in Django. 
#765
> Fixed link to offerDetail

- backend/apps/volontulo/templates/common/footer.html
- backend/apps/volontulo/templates/common/header.html
- frontend/src/app/header/header.component.html
Replaced django homepage links in templates with Angular ones.
> Replaced django homepage links in templates with Angular ones.

- backend/apps/volontulo/models.py
- backend/apps/volontulo/tests/views/test_pages.py
Admin can access all offers.
fixes #746
> Admin can access published offers

- frontend/src/app/organization/organization-contact/organization-contact.component.html
- frontend/src/app/organization/organization-contact/organization-contact.component.scss
- frontend/src/app/organization/organization-contact/organization-contact.component.ts
Honeypot method implemented for the contact form to an organization. [Hiden input in the form; submitting blocked if some value provided for this input].
> Honeypot for contact form

- backend/apps/volontulo/tests/views/api/test_password_reset.py
- backend/apps/volontulo/urls.py
- frontend/src/app/auth.service.ts
Added slashes to unify url convention.
> Added slashes to URLs to unify convention.

- frontend/src/app/organization/organization-contact/organization-contact.component.ts
- frontend/src/app/organization/organization-offers-list/organization-offers-list.component.html
Some minor changes in organization's details component to fix bugs that ware logged in the console.
> Changes in organization's detail view fixes #930

- frontend/src/app/app.module.ts
- frontend/src/app/organization/organization.service.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.html
- frontend/src/app/organizations/organizations-list/organizations-list.component.ts
- frontend/src/app/organizations/organizations.component.html
- frontend/src/app/organizations/organizations.component.ts
Refactor organizations component and extract organizations-list component. Remove unused methods from service and organizations component.
> create organizations-list component (fixes #991)

- backend/apps/volontulo/templates/common/footer.html
Contact admin url in Django footer fixed to point to Angular
> Contact admin url in Django footer fixed to point to Angular

- frontend/src/app/account/account.component.html
- frontend/src/app/account/account.component.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.html
- frontend/src/app/organizations/organizations-list/organizations-list.component.spec.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.ts
- frontend/src/app/organizations/organizations.component.html
Insert organizations list components into account component
Unit test for organizations-list components
> Account component/organizations (fixes #975)

- frontend/src/app/auth.service.spec.ts
unit tests for auth service in angular
> Unit tests for auth service fixes #601

- backend/apps/volontulo/serializers.py
- backend/apps/volontulo/tests/common.py
- backend/apps/volontulo/tests/views/api/organizations/test_list.py
- backend/apps/volontulo/tests/views/api/organizations/test_read.py
- backend/apps/volontulo/tests/views/api/test_login_view.py
- frontend/src/app/organization/organization.model.ts
Added test for login. Removed field url from organization (it was not used).
> test login

- frontend/src/app/contact/contact.component.html
- frontend/src/app/contact/contact.component.ts
add honeypot to admin contact form #1011
> [#1011] add honeypot to admin contact form

- frontend/src/app/user-profile/user-profile.component.html
Description of your changes.
* `package`
* `apps/volontulo/tests/views/test_auth.py`
> #1072 "submit" button changed to "zapisz"

- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/auth.service.spec.ts
- frontend/src/app/contact/contact.component.html
- frontend/src/app/contact/contact.component.ts
- frontend/src/app/form-error/form-error.component.html
- frontend/src/app/form-error/form-error.component.ts
- frontend/src/app/organization/organization-contact/organization-contact.component.html
- frontend/src/app/user-profile/user-profile.component.html
- frontend/src/app/user-profile/user-profile.component.spec.ts
- frontend/src/app/user-profile/user-profile.component.ts
Add phone validation via IMask
> [864] phone number validation - frontend

- frontend/src/app/auth.models.ts
- frontend/src/app/register/register.component.html
- frontend/src/app/register/register.component.ts
Adding password confirmation to user registration form
> [1074] Dodanie "Powtórz hasło" przy zakładaniu konta 

- backend/apps/volontulo/tests/views/api/test_current_user.py
- backend/apps/volontulo/views/api.py
- frontend/src/app/services/auth.service.ts
Return 200 from current_user when unlogged.
NA
test_current_user.py
NA
> [1019] Current user should return 200 when unlogged
